### ISSUE TITLE
[QUESTION]: Huffman coding table

### ISSUE THREAD

**Issue by diegocatalao** [theo-al/brainfuck-utils#1]
Is it possible to implement a solution with huffman coding?

**Comment by theo-al** [comment]
the compressor here is only meant to make brainfuck more readable (and possibly to help with optimizing in a future compiler), assuming that's what you were thinking of.

if you meant in the interpreter itself, i would think generating and using a huffman tree would likely only be good at making the interpreter run slower (especially considering brainfuck only has 8 symbols, all of which fit already fit into a byte), unless we were using it to compile to some kind of per-program bf bytecode to run later. which is an interesting idea, but it doesn't seem to me it would be useful for anything (other than maybe obfuscation (?)), even though it would obviously save a bit of disk space.

i don't think it's worth the extra complexity either way.
